[Paths]
# Adjust these however you like
# If you adjust the variable name, make sure to also adjust it in bot/config.py

checkin_file = your_desired_file_path_here
users_file = your_desired_file_path_here
sheet_cache = your_desired_file_path_here
credsPath = your_desired_file_path_here

